<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="RestSharp" />
    <PackageReference Include="RestSharp.Serializers.SystemTextJson" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TpLink.UnitTest" />
  </ItemGroup>
</Project>