<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Configurations>Debug;Release</Configurations>
        <Authors>Ivandrofly</Authors>
        <Company>Ivandrofly</Company>
        <RepositoryUrl>https://github.com/ivandrofly/tplink-powerline-api</RepositoryUrl>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

</Project>